### ISSUE TITLE
Combining references in variable causes "soft crash"

### ISSUE THREAD

**Issue by johshoff** [cdglabs/apparatus#17]
I'm trying to create a variable `i` that depends on a rectangle's `X` and `Y`. Dragging the `X` to `i` works. Multiplying by a constant works: `X*0.1`. But dragging the `Y` in the hopes of creating `X*Y` crashes it with an id-string instead of the properly styled `Y`.

JSON: https://gist.github.com/johshoff/9ca6babef61101e02478

Before:

![screen shot 2015-10-05 at 19 13 09](https://cloud.githubusercontent.com/assets/353935/10298622/f0d14e3e-6b95-11e5-81ad-9fbcdd480668.png)

After:

![screen shot 2015-10-05 at 19 15 56](https://cloud.githubusercontent.com/assets/353935/10298624/f5fb5f62-6b95-11e5-8251-0a4ae6810bef.png)

**Comment by electronicwhisper** [comment]
This is fixed (and your example works) in the latest on the master branch. I will release a new version (0.4.1) in a week or so and push all these changes to the website.

**Comment by johshoff** [comment]
Thanks! :)
