### ISSUE TITLE
Dragging RGBA values for colors not bounded

### ISSUE THREAD

**Issue by mgold** [cdglabs/apparatus#3]
When dragging the components of an rgba color, it is possible to drag them outside of the range [0, 1]. Colors should be clamped to this valid range.

**Comment by electronicwhisper** [comment]
I think you're right from a usability perspective. It gets hairy in that some numbers in the system would then need to be treated in a certain way. As of now, all numbers scrub, they always keep their decimal precision when you scrub them, and they're unbounded. This seems to work well enough in most cases.

Luckily, I think the answer to both better usability around colors and keeping number scrubbing consistent is just to have a color picker for color values. So I've opened an issue #4 for that.

I'm closing this one. Thanks for reporting!

**Comment by mgold** [comment]
That's a much better idea, thanks.
