### ISSUE TITLE
Improve selecting of objects in the outline panel 

### ISSUE THREAD

**Issue by capellsk** [cdglabs/apparatus#62]
For a beginner it's mystifying how to select objects in the Outline panel. At first it seems to not work at all. Then you find that it works once in a while. Then you realize there's a tiny area between the collapse button and the text that you have to click. Finally you reach enlightenment and discover that clicking in the blank area to the right of the content is the way to go. Life is easy after that.

Would it break anything if the object becomes selected when you click on anything in the area, including the collapse button and the name?

**Comment by joshuahhh** [comment]
It make sense to me how a beginner could have the experience you describe. Thanks for the report!

I agree with you that there is no good reason why clicking the name shouldn't select the element. I'll fix that.

But I don't think that clicking the collapse button should select the object. Collapsing/expanding parts of the tree is a "navigational" operation which you might want to perform as part of editing the selected element. For instance, you might be looking for an attribute somewhere else in the tree which you want to drop into an expression in the Inspector below. 

One comparison here is Mac Finder, where collapsing/expanding does not select the folder:

<img src="https://cloud.githubusercontent.com/assets/643799/18812167/00196924-8280-11e6-8ec5-ff9159f7f1fb.gif" alt="animation of Mac Finder" width="200">

(Thanks again!)
