### ISSUE TITLE
Reordering variables

### ISSUE THREAD

**Issue by joshuahhh** [cdglabs/apparatus#8]
Reordering variables under a shape would be friggin' great! Some kinda drag-and-drop situation?

**Comment by electronicwhisper** [comment]
Yes, and also reparenting variables, so you can put them underneath a
different element. Just have to decide how you trigger this drag operation.
Or maybe you trigger it by dropping on the left side of the column rather
than the right side (which is drop to reference). Incidentally there needs
to be drop feedback for dropping a reference; many had trouble with this in
the play test.
